# mypy: disable-error-code="arg-type, unused-ignore"
'''This module contains Bad Payload tests to be run with pytest.

The file was generated by methods of the `Tests` class in the `genedata.generate` module.

DO NOT MODIFY THIS FILE.
'''

import pytest   # noqa: I001
import re

import genedata.classes70 as gc
from genedata.build import Genealogy
from genedata.messages import Msg


g = Genealogy()
fam = g.family_xref('1')
indi = g.individual_xref('1')
obje = g.multimedia_xref('1')
repo = g.repository_xref('1')
snote = g.shared_note_xref('1', 'a note')
sour = g.source_xref('1')
subm = g.submitter_xref('1')


def test_bad_payload_Abbr() -> None:
    '''Validate the `Abbr` structure with a value and required substructures.'''
    m = gc.Abbr(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Addr() -> None:
    '''Validate the `Addr` structure with a value and required substructures.'''
    m = gc.Addr(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_AdopFamc() -> None:
    '''Validate the `AdopFamc` structure with a value and required substructures.'''
    m = gc.AdopFamc(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_FAMILY_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Adop() -> None:
    '''Validate the `Adop` structure with a value and required substructures.'''
    m = gc.Adop(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Adr1() -> None:
    '''Validate the `Adr1` structure with a value and required substructures.'''
    m = gc.Adr1(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Adr2() -> None:
    '''Validate the `Adr2` structure with a value and required substructures.'''
    m = gc.Adr2(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Adr3() -> None:
    '''Validate the `Adr3` structure with a value and required substructures.'''
    m = gc.Adr3(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Age() -> None:
    '''Validate the `Age` structure with a value and required substructures.'''
    m = gc.Age(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Agnc() -> None:
    '''Validate the `Agnc` structure with a value and required substructures.'''
    m = gc.Agnc(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Alia() -> None:
    '''Validate the `Alia` structure with a value and required substructures.'''
    m = gc.Alia(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_INDIVIDUAL_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Anci() -> None:
    '''Validate the `Anci` structure with a value and required substructures.'''
    m = gc.Anci(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_SUBMITTER_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Anul() -> None:
    '''Validate the `Anul` structure with a value and required substructures.'''
    m = gc.Anul(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Asso() -> None:
    '''Validate the `Asso` structure with a value and required substructures.'''
    m = gc.Asso(-1, gc.Role('CHIL'))
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_INDIVIDUAL_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Auth() -> None:
    '''Validate the `Auth` structure with a value and required substructures.'''
    m = gc.Auth(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Bapm() -> None:
    '''Validate the `Bapm` structure with a value and required substructures.'''
    m = gc.Bapm(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Barm() -> None:
    '''Validate the `Barm` structure with a value and required substructures.'''
    m = gc.Barm(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Basm() -> None:
    '''Validate the `Basm` structure with a value and required substructures.'''
    m = gc.Basm(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Birt() -> None:
    '''Validate the `Birt` structure with a value and required substructures.'''
    m = gc.Birt(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Bles() -> None:
    '''Validate the `Bles` structure with a value and required substructures.'''
    m = gc.Bles(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Buri() -> None:
    '''Validate the `Buri` structure with a value and required substructures.'''
    m = gc.Buri(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Caln() -> None:
    '''Validate the `Caln` structure with a value and required substructures.'''
    m = gc.Caln(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Cast() -> None:
    '''Validate the `Cast` structure with a value and required substructures.'''
    m = gc.Cast(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Caus() -> None:
    '''Validate the `Caus` structure with a value and required substructures.'''
    m = gc.Caus(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Chil() -> None:
    '''Validate the `Chil` structure with a value and required substructures.'''
    m = gc.Chil(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_INDIVIDUAL_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Chr() -> None:
    '''Validate the `Chr` structure with a value and required substructures.'''
    m = gc.Chr(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Chra() -> None:
    '''Validate the `Chra` structure with a value and required substructures.'''
    m = gc.Chra(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_City() -> None:
    '''Validate the `City` structure with a value and required substructures.'''
    m = gc.City(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Conf() -> None:
    '''Validate the `Conf` structure with a value and required substructures.'''
    m = gc.Conf(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Copr() -> None:
    '''Validate the `Copr` structure with a value and required substructures.'''
    m = gc.Copr(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Corp() -> None:
    '''Validate the `Corp` structure with a value and required substructures.'''
    m = gc.Corp(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Crem() -> None:
    '''Validate the `Crem` structure with a value and required substructures.'''
    m = gc.Crem(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Ctry() -> None:
    '''Validate the `Ctry` structure with a value and required substructures.'''
    m = gc.Ctry(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_DataEvenDate() -> None:
    '''Validate the `DataEvenDate` structure with a value and required substructures.'''
    m = gc.DataEvenDate(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_DataEven() -> None:
    '''Validate the `DataEven` structure with a value and required substructures.'''
    m = gc.DataEven(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_DateExact() -> None:
    '''Validate the `DateExact` structure with a value and required substructures.'''
    m = gc.DateExact(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Date() -> None:
    '''Validate the `Date` structure with a value and required substructures.'''
    m = gc.Date(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Deat() -> None:
    '''Validate the `Deat` structure with a value and required substructures.'''
    m = gc.Deat(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Desi() -> None:
    '''Validate the `Desi` structure with a value and required substructures.'''
    m = gc.Desi(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_SUBMITTER_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Dest() -> None:
    '''Validate the `Dest` structure with a value and required substructures.'''
    m = gc.Dest(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Div() -> None:
    '''Validate the `Div` structure with a value and required substructures.'''
    m = gc.Div(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Divf() -> None:
    '''Validate the `Divf` structure with a value and required substructures.'''
    m = gc.Divf(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Dscr() -> None:
    '''Validate the `Dscr` structure with a value and required substructures.'''
    m = gc.Dscr(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Educ() -> None:
    '''Validate the `Educ` structure with a value and required substructures.'''
    m = gc.Educ(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Email() -> None:
    '''Validate the `Email` structure with a value and required substructures.'''
    m = gc.Email(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Emig() -> None:
    '''Validate the `Emig` structure with a value and required substructures.'''
    m = gc.Emig(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Enga() -> None:
    '''Validate the `Enga` structure with a value and required substructures.'''
    m = gc.Enga(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_ExidType() -> None:
    '''Validate the `ExidType` structure with a value and required substructures.'''
    m = gc.ExidType(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Exid() -> None:
    '''Validate the `Exid` structure with a value and required substructures.'''
    m = gc.Exid(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_FamCens() -> None:
    '''Validate the `FamCens` structure with a value and required substructures.'''
    m = gc.FamCens(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_FamEven() -> None:
    '''Validate the `FamEven` structure with a value and required substructures.'''
    m = gc.FamEven(-1, gc.Type('abc'))
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_FamFact() -> None:
    '''Validate the `FamFact` structure with a value and required substructures.'''
    m = gc.FamFact(-1, gc.Type('abc'))
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_FamHusb() -> None:
    '''Validate the `FamHusb` structure with a value and required substructures.'''
    m = gc.FamHusb(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_INDIVIDUAL_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_FamNchi() -> None:
    '''Validate the `FamNchi` structure with a value and required substructures.'''
    m = gc.FamNchi(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_INTEGER.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_FamResi() -> None:
    '''Validate the `FamResi` structure with a value and required substructures.'''
    m = gc.FamResi(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_FamWife() -> None:
    '''Validate the `FamWife` structure with a value and required substructures.'''
    m = gc.FamWife(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_INDIVIDUAL_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_FamcAdop() -> None:
    '''Validate the `FamcAdop` structure with a value and required substructures.'''
    m = gc.FamcAdop(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_FamcStat() -> None:
    '''Validate the `FamcStat` structure with a value and required substructures.'''
    m = gc.FamcStat(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Famc() -> None:
    '''Validate the `Famc` structure with a value and required substructures.'''
    m = gc.Famc(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_FAMILY_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Fams() -> None:
    '''Validate the `Fams` structure with a value and required substructures.'''
    m = gc.Fams(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_FAMILY_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Fax() -> None:
    '''Validate the `Fax` structure with a value and required substructures.'''
    m = gc.Fax(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Fcom() -> None:
    '''Validate the `Fcom` structure with a value and required substructures.'''
    m = gc.Fcom(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_FileTran() -> None:
    '''Validate the `FileTran` structure with a value and required substructures.'''
    m = gc.FileTran(-1, gc.Form('text/html'))
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_File() -> None:
    '''Validate the `File` structure with a value and required substructures.'''
    m = gc.File(-1, gc.Form('text/html'))
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Form() -> None:
    '''Validate the `Form` structure with a value and required substructures.'''
    m = gc.Form(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_GedcVers() -> None:
    '''Validate the `GedcVers` structure with a value and required substructures.'''
    m = gc.GedcVers(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Givn() -> None:
    '''Validate the `Givn` structure with a value and required substructures.'''
    m = gc.Givn(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Grad() -> None:
    '''Validate the `Grad` structure with a value and required substructures.'''
    m = gc.Grad(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_HeadDate() -> None:
    '''Validate the `HeadDate` structure with a value and required substructures.'''
    m = gc.HeadDate(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_HeadLang() -> None:
    '''Validate the `HeadLang` structure with a value and required substructures.'''
    m = gc.HeadLang(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_HeadPlacForm() -> None:
    '''Validate the `HeadPlacForm` structure with a value and required substructures.'''
    m = gc.HeadPlacForm(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_HeadSourData() -> None:
    '''Validate the `HeadSourData` structure with a value and required substructures.'''
    m = gc.HeadSourData(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_HeadSour() -> None:
    '''Validate the `HeadSour` structure with a value and required substructures.'''
    m = gc.HeadSour(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Height() -> None:
    '''Validate the `Height` structure with a value and required substructures.'''
    m = gc.Height(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_INTEGER.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Idno() -> None:
    '''Validate the `Idno` structure with a value and required substructures.'''
    m = gc.Idno(-1, gc.Type('abc'))
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Immi() -> None:
    '''Validate the `Immi` structure with a value and required substructures.'''
    m = gc.Immi(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_IndiCens() -> None:
    '''Validate the `IndiCens` structure with a value and required substructures.'''
    m = gc.IndiCens(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_IndiEven() -> None:
    '''Validate the `IndiEven` structure with a value and required substructures.'''
    m = gc.IndiEven(-1, gc.Type('abc'))
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_IndiFact() -> None:
    '''Validate the `IndiFact` structure with a value and required substructures.'''
    m = gc.IndiFact(-1, gc.Type('abc'))
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_IndiFamc() -> None:
    '''Validate the `IndiFamc` structure with a value and required substructures.'''
    m = gc.IndiFamc(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_FAMILY_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_IndiName() -> None:
    '''Validate the `IndiName` structure with a value and required substructures.'''
    m = gc.IndiName(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_IndiNchi() -> None:
    '''Validate the `IndiNchi` structure with a value and required substructures.'''
    m = gc.IndiNchi(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_INTEGER.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_IndiReli() -> None:
    '''Validate the `IndiReli` structure with a value and required substructures.'''
    m = gc.IndiReli(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_IndiResi() -> None:
    '''Validate the `IndiResi` structure with a value and required substructures.'''
    m = gc.IndiResi(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_IndiTitl() -> None:
    '''Validate the `IndiTitl` structure with a value and required substructures.'''
    m = gc.IndiTitl(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Lang() -> None:
    '''Validate the `Lang` structure with a value and required substructures.'''
    m = gc.Lang(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Lati() -> None:
    '''Validate the `Lati` structure with a value and required substructures.'''
    m = gc.Lati(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Left() -> None:
    '''Validate the `Left` structure with a value and required substructures.'''
    m = gc.Left(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_INTEGER.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Long() -> None:
    '''Validate the `Long` structure with a value and required substructures.'''
    m = gc.Long(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Marb() -> None:
    '''Validate the `Marb` structure with a value and required substructures.'''
    m = gc.Marb(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Marc() -> None:
    '''Validate the `Marc` structure with a value and required substructures.'''
    m = gc.Marc(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Marl() -> None:
    '''Validate the `Marl` structure with a value and required substructures.'''
    m = gc.Marl(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Marr() -> None:
    '''Validate the `Marr` structure with a value and required substructures.'''
    m = gc.Marr(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Mars() -> None:
    '''Validate the `Mars` structure with a value and required substructures.'''
    m = gc.Mars(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Medi() -> None:
    '''Validate the `Medi` structure with a value and required substructures.'''
    m = gc.Medi(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Mime() -> None:
    '''Validate the `Mime` structure with a value and required substructures.'''
    m = gc.Mime(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_NameTran() -> None:
    '''Validate the `NameTran` structure with a value and required substructures.'''
    m = gc.NameTran(-1, gc.Lang('en-US'))
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_NameType() -> None:
    '''Validate the `NameType` structure with a value and required substructures.'''
    m = gc.NameType(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Name() -> None:
    '''Validate the `Name` structure with a value and required substructures.'''
    m = gc.Name(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Nati() -> None:
    '''Validate the `Nati` structure with a value and required substructures.'''
    m = gc.Nati(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Natu() -> None:
    '''Validate the `Natu` structure with a value and required substructures.'''
    m = gc.Natu(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Nick() -> None:
    '''Validate the `Nick` structure with a value and required substructures.'''
    m = gc.Nick(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Nmr() -> None:
    '''Validate the `Nmr` structure with a value and required substructures.'''
    m = gc.Nmr(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_INTEGER.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_NoDate() -> None:
    '''Validate the `NoDate` structure with a value and required substructures.'''
    m = gc.NoDate(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_No() -> None:
    '''Validate the `No` structure with a value and required substructures.'''
    m = gc.No(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_NoteTran() -> None:
    '''Validate the `NoteTran` structure with a value and required substructures.'''
    m = gc.NoteTran(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Note() -> None:
    '''Validate the `Note` structure with a value and required substructures.'''
    m = gc.Note(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Npfx() -> None:
    '''Validate the `Npfx` structure with a value and required substructures.'''
    m = gc.Npfx(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Nsfx() -> None:
    '''Validate the `Nsfx` structure with a value and required substructures.'''
    m = gc.Nsfx(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Obje() -> None:
    '''Validate the `Obje` structure with a value and required substructures.'''
    m = gc.Obje(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_MULTIMEDIA_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Occu() -> None:
    '''Validate the `Occu` structure with a value and required substructures.'''
    m = gc.Occu(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_OrdStat() -> None:
    '''Validate the `OrdStat` structure with a value and required substructures.'''
    m = gc.OrdStat(-1, gc.DateExact('1 JAN 2000'))
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Ordn() -> None:
    '''Validate the `Ordn` structure with a value and required substructures.'''
    m = gc.Ordn(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Page() -> None:
    '''Validate the `Page` structure with a value and required substructures.'''
    m = gc.Page(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Pedi() -> None:
    '''Validate the `Pedi` structure with a value and required substructures.'''
    m = gc.Pedi(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Phon() -> None:
    '''Validate the `Phon` structure with a value and required substructures.'''
    m = gc.Phon(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Phrase() -> None:
    '''Validate the `Phrase` structure with a value and required substructures.'''
    m = gc.Phrase(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_PlacForm() -> None:
    '''Validate the `PlacForm` structure with a value and required substructures.'''
    m = gc.PlacForm(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_PlacTran() -> None:
    '''Validate the `PlacTran` structure with a value and required substructures.'''
    m = gc.PlacTran(-1, gc.Lang('en-US'))
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Plac() -> None:
    '''Validate the `Plac` structure with a value and required substructures.'''
    m = gc.Plac(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Post() -> None:
    '''Validate the `Post` structure with a value and required substructures.'''
    m = gc.Post(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Prob() -> None:
    '''Validate the `Prob` structure with a value and required substructures.'''
    m = gc.Prob(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Prop() -> None:
    '''Validate the `Prop` structure with a value and required substructures.'''
    m = gc.Prop(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Publ() -> None:
    '''Validate the `Publ` structure with a value and required substructures.'''
    m = gc.Publ(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Quay() -> None:
    '''Validate the `Quay` structure with a value and required substructures.'''
    m = gc.Quay(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_RecordSnote() -> None:
    '''Validate the `RecordSnote` structure with a value and required substructures.'''
    m = gc.RecordSnote(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_SHARED_NOTE_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Refn() -> None:
    '''Validate the `Refn` structure with a value and required substructures.'''
    m = gc.Refn(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Reli() -> None:
    '''Validate the `Reli` structure with a value and required substructures.'''
    m = gc.Reli(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Repo() -> None:
    '''Validate the `Repo` structure with a value and required substructures.'''
    m = gc.Repo(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_REPOSITORY_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Resn() -> None:
    '''Validate the `Resn` structure with a value and required substructures.'''
    m = gc.Resn(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Reti() -> None:
    '''Validate the `Reti` structure with a value and required substructures.'''
    m = gc.Reti(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Role() -> None:
    '''Validate the `Role` structure with a value and required substructures.'''
    m = gc.Role(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Sdate() -> None:
    '''Validate the `Sdate` structure with a value and required substructures.'''
    m = gc.Sdate(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Sex() -> None:
    '''Validate the `Sex` structure with a value and required substructures.'''
    m = gc.Sex(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Snote() -> None:
    '''Validate the `Snote` structure with a value and required substructures.'''
    m = gc.Snote(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_SHARED_NOTE_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_SourEven() -> None:
    '''Validate the `SourEven` structure with a value and required substructures.'''
    m = gc.SourEven(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Sour() -> None:
    '''Validate the `Sour` structure with a value and required substructures.'''
    m = gc.Sour(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_SOURCE_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Spfx() -> None:
    '''Validate the `Spfx` structure with a value and required substructures.'''
    m = gc.Spfx(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Ssn() -> None:
    '''Validate the `Ssn` structure with a value and required substructures.'''
    m = gc.Ssn(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Stae() -> None:
    '''Validate the `Stae` structure with a value and required substructures.'''
    m = gc.Stae(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_SubmLang() -> None:
    '''Validate the `SubmLang` structure with a value and required substructures.'''
    m = gc.SubmLang(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Subm() -> None:
    '''Validate the `Subm` structure with a value and required substructures.'''
    m = gc.Subm(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_SUBMITTER_XREF.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Surn() -> None:
    '''Validate the `Surn` structure with a value and required substructures.'''
    m = gc.Surn(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Tag() -> None:
    '''Validate the `Tag` structure with a value and required substructures.'''
    m = gc.Tag(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Temp() -> None:
    '''Validate the `Temp` structure with a value and required substructures.'''
    m = gc.Temp(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Text() -> None:
    '''Validate the `Text` structure with a value and required substructures.'''
    m = gc.Text(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Time() -> None:
    '''Validate the `Time` structure with a value and required substructures.'''
    m = gc.Time(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Titl() -> None:
    '''Validate the `Titl` structure with a value and required substructures.'''
    m = gc.Titl(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Top() -> None:
    '''Validate the `Top` structure with a value and required substructures.'''
    m = gc.Top(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_INTEGER.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Type() -> None:
    '''Validate the `Type` structure with a value and required substructures.'''
    m = gc.Type(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Uid() -> None:
    '''Validate the `Uid` structure with a value and required substructures.'''
    m = gc.Uid(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Vers() -> None:
    '''Validate the `Vers` structure with a value and required substructures.'''
    m = gc.Vers(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Width() -> None:
    '''Validate the `Width` structure with a value and required substructures.'''
    m = gc.Width(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_INTEGER.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Will() -> None:
    '''Validate the `Will` structure with a value and required substructures.'''
    m = gc.Will(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()


def test_bad_payload_Www() -> None:
    '''Validate the `Www` structure with a value and required substructures.'''
    m = gc.Www(-1)
    with pytest.raises(
        ValueError, match=re.escape(Msg.NOT_STRING.format('-1', m.class_name))
    ):
        assert m.validate()
