# french_revolution_calendars
"""Definitions for various forms of the French Revolution calendars."""

import numpy as np

from calendars.calendars import (
    CalendarDefinition,
    DayDefinition,
    MonthDefinition,
    WeekDayDefinition,
    YearDefinition,
)


class CalendarsFrenchRevolution:
    FRENCH_R = CalendarDefinition(
        name='French Revolution',
        years=YearDefinition(np.timedelta64(0, 'Y'),np.timedelta64(0, 'M'),np.timedelta64(0, 'D')),
        months=[
            MonthDefinition(0, '', days=0, abbreviation=''), 
            MonthDefinition(1, 'Vendémiaire', symbol='', days=30, abbreviation='VEND'),
            MonthDefinition(2, 'Brumaire', symbol='', days=30, abbreviation='BRUM'),
            MonthDefinition(3, 'Frimaire', symbol='', days=30, abbreviation='FRIM'),
            MonthDefinition(4, 'Nivôse', symbol='', days=30, abbreviation='NIVO'),
            MonthDefinition(5, 'Pluviôse', symbol='', days=30, abbreviation='PLUV'),
            MonthDefinition(6, 'Ventôse', symbol='', days=30, abbreviation='VENT'),
            MonthDefinition(7, 'Germinal', symbol='', days=30, abbreviation='GERM'),
            MonthDefinition(8, 'Floréal', symbol='', days=30, abbreviation='FLOR'),
            MonthDefinition(9, 'Prairial', symbol='', days=30, abbreviation='PRAI'),
            MonthDefinition(10, 'Messidor', symbol='', days=30, abbreviation='MESS'),
            MonthDefinition(11, 'Thermidor', symbol='', days=30, abbreviation='THER'),
            MonthDefinition(12, 'Fructidor', symbol='', days=30, abbreviation='FRUC'),
            MonthDefinition(13, 'Comp', symbol='', days=5, abbreviation='COMP'),
        ],
        weeks=[],
        weekdays=[
            WeekDayDefinition(1, 'primidi', symbol=''),
            WeekDayDefinition(2,'duodi', symbol=''),
            WeekDayDefinition(3,'tridi', symbol=''),
            WeekDayDefinition(4,'quartidi', symbol=''),
            WeekDayDefinition(5,'quintidi', symbol=''),
            WeekDayDefinition(6,'sextidi', symbol=''),
            WeekDayDefinition(7,'septidi', symbol=''),
            WeekDayDefinition(8,'octidi', symbol=''),
            WeekDayDefinition(9,'nonidi', symbol=''),
            WeekDayDefinition(10,'décadi', symbol=''),
        ],
        days=[
            DayDefinition(1, 'Raisin', 1),
            DayDefinition(2, 'Safran', 1),
            DayDefinition(3, 'Châtaigne', 1),
            DayDefinition(4, 'Colchique', 1),
            DayDefinition(5, 'Cheval', 1),
            DayDefinition(6, 'Balsamine', 1),
            DayDefinition(7, 'Carotte', 1),
            DayDefinition(8, 'Amaranthe', 1),
            DayDefinition(9, 'Panais', 1),
            DayDefinition(10, 'Cuve', 1),
            DayDefinition(11, 'Pomme de terre', 1),
            DayDefinition(12, 'Immortelle', 1),
            DayDefinition(13, 'Potiron', 1),
            DayDefinition(14, 'Réséda', 1),
            DayDefinition(15, 'Âne', 1),
            DayDefinition(16, 'Belle de nuit', 1),
            DayDefinition(17, 'Citrouille', 1),
            DayDefinition(18, 'Sarrasin', 1),
            DayDefinition(19, 'Tournesol', 1),
            DayDefinition(20, 'Pressoir', 1),
            DayDefinition(21, 'Chanvre', 1),
            DayDefinition(22, 'Pêche', 1),
            DayDefinition(23, 'Navet', 1),
            DayDefinition(24, 'Amaryllis', 1),
            DayDefinition(25, 'Bœuf', 1),
            DayDefinition(26, 'Aubergine', 1),
            DayDefinition(27, 'Piment', 1),
            DayDefinition(28, 'Tomate', 1),
            DayDefinition(29, 'Orge', 1),
            DayDefinition(30, 'Tonneau', 1),
            DayDefinition(31, 'Pomme', 2),
            DayDefinition(32, 'Céleri', 2),
            DayDefinition(33, 'Poire', 2),
            DayDefinition(34, 'Betterave', 2),
            DayDefinition(35, 'Oie', 2),
            DayDefinition(36, 'Héliotrope', 2),
            DayDefinition(37, 'Figue', 2),
            DayDefinition(38, 'Scorsonère', 2),
            DayDefinition(39, 'Alisier', 2),
            DayDefinition(40, 'Charrue', 2),
            DayDefinition(41, 'Salsifis', 2),
            DayDefinition(42, 'Mâcre', 2),
            DayDefinition(43, 'Topinambour', 2),
            DayDefinition(44, 'Endive', 2),
            DayDefinition(45, 'Dindon', 2),
            DayDefinition(46, 'Chervis', 2),
            DayDefinition(47, 'Cresson', 2),
            DayDefinition(48, 'Dentelaire', 2),
            DayDefinition(49, 'Grenade', 2),
            DayDefinition(50, 'Herse', 2),
            DayDefinition(51, 'Bacchante', 2),
            DayDefinition(52, 'Azerole', 2),
            DayDefinition(53, 'Garance', 2),
            DayDefinition(54, 'Orange', 2),
            DayDefinition(55, 'Faisan', 2),
            DayDefinition(56, 'Pistache', 2),
            DayDefinition(57, 'Macjonc', 2),
            DayDefinition(58, 'Coing', 2),
            DayDefinition(59, 'Cormier', 2),
            DayDefinition(60, 'Rouleau', 2),
            DayDefinition(61, 'Raiponce', 3),
            DayDefinition(62, 'Turneps', 3),
            DayDefinition(63, 'Chicorée', 3),
            DayDefinition(64, 'Nèfle', 3),
            DayDefinition(65, 'Cochon', 3),
            DayDefinition(66, 'Mâche', 3),
            DayDefinition(67, 'Chou-fleur', 3),
            DayDefinition(68, 'Miel', 3),
            DayDefinition(69, 'Genièvre', 3),
            DayDefinition(70, 'Pioche', 3),
            DayDefinition(71, 'Cire', 3),
            DayDefinition(72, 'Raifort', 3),
            DayDefinition(73, 'Cèdre', 3),
            DayDefinition(74, 'Sapin', 3),
            DayDefinition(75, 'Chevreuil', 3),
            DayDefinition(76, 'Ajonc', 3),
            DayDefinition(77, 'Cyprès', 3),
            DayDefinition(78, 'Lierre', 3),
            DayDefinition(79, 'Sabine', 3),
            DayDefinition(80, 'Hoyau', 3),
            DayDefinition(81, 'Érable à sucre', 3),
            DayDefinition(82, 'Bruyère', 3),
            DayDefinition(83, 'Roseau', 3),
            DayDefinition(84, 'Oseille', 3),
            DayDefinition(85, 'Grillon', 3),
            DayDefinition(86, 'Pignon', 3),
            DayDefinition(87, 'Liège', 3),
            DayDefinition(88, 'Truffe', 3),
            DayDefinition(89, 'Olive', 3),
            DayDefinition(90, 'Pelle', 3),
            DayDefinition(91, 'Tourbe', 4),
            DayDefinition(92, 'Houille', 4),
            DayDefinition(93, 'Bitume', 4),
            DayDefinition(94, 'Soufre', 4),
            DayDefinition(95, 'Chien', 4),
            DayDefinition(96, 'Lave', 4),
            DayDefinition(97, 'Terre végétale', 4),
            DayDefinition(98, 'Fumier', 4),
            DayDefinition(99, 'Salpêtre', 4),
            DayDefinition(100, 'Fléau', 4),
            DayDefinition(101, 'Granit', 4),
            DayDefinition(102, 'Argile', 4),
            DayDefinition(103, 'Ardoise', 4),
            DayDefinition(104, 'Grès', 4),
            DayDefinition(105, 'Lapin', 4),
            DayDefinition(106, 'Silex', 4),
            DayDefinition(107, 'Marne', 4),
            DayDefinition(108, 'Pierre à chaux', 4),
            DayDefinition(109, 'Marbre', 4),
            DayDefinition(110, 'Van', 4),
            DayDefinition(111, 'Pierre à plâtre', 4),
            DayDefinition(112, 'Sel', 4),
            DayDefinition(113, 'Fer', 4),
            DayDefinition(114, 'Cuivre', 4),
            DayDefinition(115, 'Chat', 4),
            DayDefinition(116, 'Étain', 4),
            DayDefinition(117, 'Plom', 4),
            DayDefinition(118, 'Zinc', 4),
            DayDefinition(119, 'Mercure', 4),
            DayDefinition(120, 'Crible', 4),
            DayDefinition(121, 'Lauréole', 5),
            DayDefinition(122, 'Mousse', 5),
            DayDefinition(123, 'Fragon', 5),
            DayDefinition(124, 'Perce-neige', 5),
            DayDefinition(125, 'Taureau', 5),
            DayDefinition(126, 'Laurier-thym', 5),
            DayDefinition(127, 'Amadouvier', 5),
            DayDefinition(128, 'Mézéréon', 5),
            DayDefinition(129, 'Peuplier', 5),
            DayDefinition(130, 'Coignée', 5),
            DayDefinition(131, 'Ellébore', 5),
            DayDefinition(132, 'Brocoli', 5),
            DayDefinition(133, 'Laurier', 5),
            DayDefinition(134, 'Avelinier', 5),
            DayDefinition(135, 'Vache', 5),
            DayDefinition(136, 'Buis', 5),
            DayDefinition(137, 'Lichen', 5),
            DayDefinition(138, 'If', 5),
            DayDefinition(139, 'Pulmonaire', 5),
            DayDefinition(140, 'Serpette', 5),
            DayDefinition(141, 'Thlaspi ', 5),
            DayDefinition(142, 'Thimelé', 5),
            DayDefinition(143, 'Chiendent', 5),
            DayDefinition(144, 'Trainasse', 5),
            DayDefinition(145, 'Lièvre', 5),
            DayDefinition(146, 'Guède', 5),
            DayDefinition(147, 'Noisetier', 5),
            DayDefinition(148, 'Cyclamen', 5),
            DayDefinition(149, 'Chélidoine', 5),
            DayDefinition(150, 'Traîneau', 5),
            DayDefinition(151, 'Tussilage', 6),
            DayDefinition(152, 'Cornouiller', 6),
            DayDefinition(153, 'Violier', 6),
            DayDefinition(154, 'Troène', 6),
            DayDefinition(155, 'Bouc', 6),
            DayDefinition(156, 'Asaret', 6),
            DayDefinition(157, 'Alaterne', 6),
            DayDefinition(158, 'Violette', 6),
            DayDefinition(159, 'Marceau', 6),
            DayDefinition(160, 'Bêche', 6),
            DayDefinition(161, 'Narcisse', 6),
            DayDefinition(162, 'Orme', 6),
            DayDefinition(163, 'Fumeterre', 6),
            DayDefinition(164, 'Vélar', 6),
            DayDefinition(165, 'Chèvre', 6),
            DayDefinition(166, 'Épinard', 6),
            DayDefinition(167, 'Doronic', 6),
            DayDefinition(168, 'Mouron', 6),
            DayDefinition(169, 'Cerfeuil', 6),
            DayDefinition(170, 'Cordeau', 6),
            DayDefinition(171, 'Mandragore', 6),
            DayDefinition(172, 'Persil', 6),
            DayDefinition(173, 'Cochléaria', 6),
            DayDefinition(174, 'Pâquerette', 6),
            DayDefinition(175, 'Thon', 6),
            DayDefinition(176, 'Pissenlit', 6),
            DayDefinition(177, 'Sylvie', 6),
            DayDefinition(178, 'Capillaire', 6),
            DayDefinition(179, 'Frêne', 6),
            DayDefinition(180, 'Plantoir', 6),
            DayDefinition(181, 'Primevère', 7),
            DayDefinition(182, 'Platane', 7),
            DayDefinition(183, 'Asperge', 7),
            DayDefinition(184, 'Tulipe', 7),
            DayDefinition(185, 'Poule', 7),
            DayDefinition(186, 'Bette', 7),
            DayDefinition(187, 'Bouleau', 7),
            DayDefinition(188, 'Jonquille', 7),
            DayDefinition(189, 'Aulne', 7),
            DayDefinition(190, 'Couvoir', 7),
            DayDefinition(191, 'Pervenche', 7),
            DayDefinition(192, 'Charme', 7),
            DayDefinition(193, 'Morille', 7),
            DayDefinition(194, 'Hêtre', 7),
            DayDefinition(195, 'Abeille', 7),
            DayDefinition(196, 'Laitue', 7),
            DayDefinition(197, 'Mélèze', 7),
            DayDefinition(198, 'Ciguë', 7),
            DayDefinition(199, 'Radis', 7),
            DayDefinition(200, 'Ruche', 7),
            DayDefinition(201, 'Gainier', 7),
            DayDefinition(202, 'Romaine', 7),
            DayDefinition(203, 'Marronnier', 7),
            DayDefinition(204, 'Roquette', 7),
            DayDefinition(205, 'Pigeon', 7),
            DayDefinition(206, 'Lilas', 7),
            DayDefinition(207, 'Anémone', 7),
            DayDefinition(208, 'Pensée', 7),
            DayDefinition(209, 'Myrtille', 7),
            DayDefinition(210, 'Greffoir', 7),
            DayDefinition(211, 'Rose', 8),
            DayDefinition(212, 'Chêne', 8),
            DayDefinition(213, 'Fougère', 8),
            DayDefinition(214, 'Aubépine', 8),
            DayDefinition(215, 'Rossignol', 8),
            DayDefinition(216, 'Ancolie', 8),
            DayDefinition(217, 'Muguet', 8),
            DayDefinition(218, 'Champignon', 8),
            DayDefinition(219, 'Hyacinthe', 8),
            DayDefinition(220, 'Râteau', 8),
            DayDefinition(221, 'Rhubarbe', 8),
            DayDefinition(222, 'Sainfoin', 8),
            DayDefinition(223, "Bâton d'or", 8),
            DayDefinition(224, 'Chamerisier', 8),
            DayDefinition(225, 'Ver à soie', 8),
            DayDefinition(226, 'Consoude', 8),
            DayDefinition(227, 'Pimprenelle', 8),
            DayDefinition(228, "Corbeille d'or", 8),
            DayDefinition(229, 'Arroche', 8),
            DayDefinition(230, 'Sarcloir', 8),
            DayDefinition(231, 'Statice', 8),
            DayDefinition(232, 'Fritillaire', 8),
            DayDefinition(233, 'Bourrache', 8),
            DayDefinition(234, 'Valériane', 8),
            DayDefinition(235, 'Carpe', 8),
            DayDefinition(236, 'usain', 8),
            DayDefinition(237, 'Civette', 8),
            DayDefinition(238, 'Buglosse', 8),
            DayDefinition(239, 'Sénevé', 8),
            DayDefinition(240, 'Houlette', 8),
            DayDefinition(241, 'Luzerne', 9),
            DayDefinition(242, 'Hémérocalle', 9),
            DayDefinition(243, 'Trèfle', 9),
            DayDefinition(244, 'Angélique', 9),
            DayDefinition(245, 'Canard', 9),
            DayDefinition(246, 'Mélisse', 9),
            DayDefinition(247, 'Fromental', 9),
            DayDefinition(248, 'Martagon', 9),
            DayDefinition(249, 'Serpolet', 9),
            DayDefinition(250, 'Faux', 9),
            DayDefinition(251, 'Fraise', 9),
            DayDefinition(252, 'Bétoine', 9),
            DayDefinition(253, 'Pois', 9),
            DayDefinition(254, 'Acacia', 9),
            DayDefinition(255, 'Caille', 9),
            DayDefinition(256, 'Œillet', 9),
            DayDefinition(257, 'Sureau', 9),
            DayDefinition(258, 'Pavot', 9),
            DayDefinition(259, 'Tilleul', 9),
            DayDefinition(260, 'Fourche', 9),
            DayDefinition(261, 'Barbeau', 9),
            DayDefinition(262, 'Camomille', 9),
            DayDefinition(263, 'Chèvrefeuille', 9),
            DayDefinition(264, 'Caille-lait', 9),
            DayDefinition(265, 'Tanche', 9),
            DayDefinition(266, 'Jasmin', 9),
            DayDefinition(267, 'Verveine', 9),
            DayDefinition(268, 'Thym', 9),
            DayDefinition(269, 'Pivoine', 9),
            DayDefinition(270, 'Chariot', 9),
            DayDefinition(271, 'Seigle', 10),
            DayDefinition(272, 'Avoine', 10),
            DayDefinition(273, 'Oignon', 10),
            DayDefinition(274, 'Véronique', 10),
            DayDefinition(275, 'Mulet', 10),
            DayDefinition(276, 'Romarin', 10),
            DayDefinition(277, 'Concombre', 10),
            DayDefinition(278, 'Échalote', 10),
            DayDefinition(279, 'Absinthe', 10),
            DayDefinition(280, 'Faucille', 10),
            DayDefinition(281, 'Coriandre', 10),
            DayDefinition(282, 'Artichaut', 10),
            DayDefinition(283, 'Girofle', 10),
            DayDefinition(284, 'Lavande', 10),
            DayDefinition(285, 'Chamois', 10),
            DayDefinition(286, 'Tabac', 10),
            DayDefinition(287, 'Groseille', 10),
            DayDefinition(288, 'Gesse', 10),
            DayDefinition(289, 'Cerise', 10),
            DayDefinition(290, 'Parc', 10),
            DayDefinition(291, 'Menthe', 10),
            DayDefinition(292, 'Cumin', 10),
            DayDefinition(293, 'Haricot', 10),
            DayDefinition(294, 'Orcanète', 10),
            DayDefinition(295, 'Pintade', 10),
            DayDefinition(296, 'Sauge', 10),
            DayDefinition(297, 'Ail', 10),
            DayDefinition(298, 'Vesce', 10),
            DayDefinition(299, 'Blé', 10),
            DayDefinition(300, 'Chalémie', 10),
            DayDefinition(301, 'Épeautre', 11),
            DayDefinition(302, 'Bouillon blanc', 11),
            DayDefinition(303, 'Melon', 11),
            DayDefinition(304, 'Ivraie', 11),
            DayDefinition(305, 'Bélier', 11),
            DayDefinition(306, 'Prêle', 11),
            DayDefinition(307, 'Armoise', 11),
            DayDefinition(308, 'Carthame', 11),
            DayDefinition(309, 'Mûre', 11),
            DayDefinition(310, 'Arrosoir', 11),
            DayDefinition(311, 'Panic', 11),
            DayDefinition(312, 'Salicorne', 11),
            DayDefinition(313, 'Abricot', 11),
            DayDefinition(314, 'Basilic', 11),
            DayDefinition(315, 'Brebis', 11),
            DayDefinition(316, 'Guimauve', 11),
            DayDefinition(317, 'Lin', 11),
            DayDefinition(318, 'Amande', 11),
            DayDefinition(319, 'Gentiane', 11),
            DayDefinition(320, 'Écluse', 11),
            DayDefinition(321, 'Carline', 11),
            DayDefinition(322, 'Câprier', 11),
            DayDefinition(323, 'Lentille', 11),
            DayDefinition(324, 'Aunée', 11),
            DayDefinition(325, 'Loutre', 11),
            DayDefinition(326, 'Myrte', 11),
            DayDefinition(327, 'Colza', 11),
            DayDefinition(328, 'Lupin', 11),
            DayDefinition(329, 'Coton', 11),
            DayDefinition(330, 'Moulin', 11),
            DayDefinition(331, 'Prune', 12),
            DayDefinition(332, 'Millet', 12),
            DayDefinition(333, 'Lycoperdon', 12),
            DayDefinition(334, 'Escourgeon', 12),
            DayDefinition(335, 'Saumon', 12),
            DayDefinition(336, 'Tubéreuse', 12),
            DayDefinition(337, 'Sucrion', 12),
            DayDefinition(338, 'Apocyn', 12),
            DayDefinition(339, 'églisse', 12),
            DayDefinition(340, 'Échelle', 12),
            DayDefinition(341, 'Pastèque', 12),
            DayDefinition(342, 'Fenouil', 12),
            DayDefinition(343, 'Épine vinette', 12),
            DayDefinition(344, 'Noix', 12),
            DayDefinition(345, 'Truite', 12),
            DayDefinition(346, 'Citron', 12),
            DayDefinition(347, 'Cardère', 12),
            DayDefinition(348, 'erprun', 12),
            DayDefinition(349, 'Tagette', 12),
            DayDefinition(350, 'Hotte', 12),
            DayDefinition(351, 'Églantier', 12),
            DayDefinition(352, 'Noisette', 12),
            DayDefinition(353, 'Houblon', 12),
            DayDefinition(354, 'Sorgho', 12),
            DayDefinition(355, 'Écrevisse', 12),
            DayDefinition(356, 'Bigarade', 12),
            DayDefinition(357, "Verge d'or", 12),
            DayDefinition(358, 'Maïs', 12),
            DayDefinition(359, 'Panier', 12),
            DayDefinition(360, '', 12),
            DayDefinition(361, '', 13),
            DayDefinition(362, '', 13),
            DayDefinition(363, '', 13),
            DayDefinition(364, '', 13),
            DayDefinition(365, '', 13),
            DayDefinition(366, '', 13),
        ],
        holidays=[],
        epoch_year=np.datetime64('1792-09-22', 'Y'),
        epoch_month=np.datetime64('1792-09-22', 'M'),
        epoch_day=np.datetime64('1792-09-22', 'D'),
        zero=False,
        negative=False,
        end=np.datetime64('1806-04-11'),
        description='',
    )