# Licensed under a 3-clause BSD style license - see LICENSE.md
"""Add a dictionary to find the ISO 639-1 language code."""

from typing import ClassVar


class Lang:
    """ISO 639-1 codes for languages.

    The GEDCOM standard requires the use of ISO 639-1 codes for
    languages. These are identified with names and then placed
    in an enumeration list.  There are less than 200 of these
    codes.  

    Reference:
        - [Library of Congress Data](https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt)
        - [ISO 639-1 and 639-2 Library of Congress](https://www.loc.gov/standards/iso639-2/langhome.html#top)
        - [ISO-1 Maintenance Agency](http://www.infoterm.info/standardization/iso_639_1_2002.php)
        - [ISO Language Standards](https://www.iso.org/iso-639-language-code)
        - [GEDCOM Standard]()
    """

    CODE: ClassVar = {
            'Afar': 'aa',
        'Abkhazian': 'ab',
        'Afrikaans': 'af',
        'Akan': 'ak',
        'Albanian': 'sq',
        'Amharic': 'am',
        'Arabic': 'ar',
        'Aragonese': 'an',
        'Armenian': 'hy',
        'Assamese': 'as',
        'Avaric': 'av',
        'Avestan': 'ae',
        'Aymara': 'ay',
        'Azerbaijani': 'az',
        'Bashkir': 'ba',
        'Bambara': 'bm',
        'Basque': 'eu',
        'Belarusian': 'be',
        'Bengali': 'bn',
        'Bislama': 'bi',
        'Bosnian': 'bs',
        'Breton': 'br',
        'Bulgarian': 'bg',
        'Burmese': 'my',
        'Catalan; Valencian': 'ca',
        'Chamorro': 'ch',
        'Chechen': 'ce',
        'Chinese': 'zh',
        'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic': 'cu',
        'Chuvash': 'cv',
        'Cornish': 'kw',
        'Corsican': 'co',
        'Cree': 'cr',
        'Czech': 'cs',
        'Danish': 'da',
        'Divehi; Dhivehi; Maldivian': 'dv',
        'Dutch; Flemish': 'nl',
        'Dzongkha': 'dz',
        'English': 'en',
        'Esperanto': 'eo',
        'Estonian': 'et',
        'Ewe': 'ee',
        'Faroese': 'fo',
        'Fijian': 'fj',
        'Finnish': 'fi',
        'French': 'fr',
        'Western Frisian': 'fy',
        'Fulah': 'ff',
        'Georgian': 'ka',
        'German': 'de',
        'Gaelic; Scottish Gaelic': 'gd',
        'Irish': 'ga',
        'Galician': 'gl',
        'Manx': 'gv',
        'Greek, Modern (1453-)': 'el',
        'Guarani': 'gn',
        'Gujarati': 'gu',
        'Haitian; Haitian Creole': 'ht',
        'Hausa': 'ha',
        'Hebrew': 'he',
        'Herero': 'hz',
        'Hindi': 'hi',
        'Hiri Motu': 'ho',
        'Croatian': 'hr',
        'Hungarian': 'hu',
        'Igbo': 'ig',
        'Icelandic': 'is',
        'Ido': 'io',
        'Sichuan Yi; Nuosu': 'ii',
        'Inuktitut': 'iu',
        'Interlingue; Occidental': 'ie',
        'Interlingua (International Auxiliary Language Association)': 'ia',
        'Indonesian': 'id',
        'Inupiaq': 'ik',
        'Italian': 'it',
        'Javanese': 'jv',
        'Japanese': 'ja',
        'Kalaallisut; Greenlandic': 'kl',
        'Kannada': 'kn',
        'Kashmiri': 'ks',
        'Kanuri': 'kr',
        'Kazakh': 'kk',
        'Central Khmer': 'km',
        'Kikuyu; Gikuyu': 'ki',
        'Kinyarwanda': 'rw',
        'Kirghiz; Kyrgyz': 'ky',
        'Komi': 'kv',
        'Kongo': 'kg',
        'Korean': 'ko',
        'Kuanyama; Kwanyama': 'kj',
        'Kurdish': 'ku',
        'Lao': 'lo',
        'Latin': 'la',
        'Latvian': 'lv',
        'Limburgan; Limburger; Limburgish': 'li',
        'Lingala': 'ln',
        'Lithuanian': 'lt',
        'Luxembourgish; Letzeburgesch': 'lb',
        'Luba-Katanga': 'lu',
        'Ganda': 'lg',
        'Macedonian': 'mk',
        'Marshallese': 'mh',
        'Malayalam': 'ml',
        'Maori': 'mi',
        'Marathi': 'mr',
        'Malay': 'ms',
        'Malagasy': 'mg',
        'Maltese': 'mt',
        'Mongolian': 'mn',
        'Nauru': 'na',
        'Navajo; Navaho': 'nv',
        'Ndebele, South; South Ndebele': 'nr',
        'Ndebele, North; North Ndebele': 'nd',
        'Ndonga': 'ng',
        'Nepali': 'ne',
        'Norwegian Nynorsk; Nynorsk, Norwegian': 'nn',
        'Bokmål, Norwegian; Norwegian Bokmål': 'nb',
        'Norwegian': 'no',
        'Chichewa; Chewa; Nyanja': 'ny',
        'Occitan (post 1500)': 'oc',
        'Ojibwa': 'oj',
        'Oriya': 'or',
        'Oromo': 'om',
        'Ossetian; Ossetic': 'os',
        'Panjabi; Punjabi': 'pa',
        'Persian': 'fa',
        'Pali': 'pi',
        'Polish': 'pl',
        'Portuguese': 'pt',
        'Pushto; Pashto': 'ps',
        'Quechua': 'qu',
        'Romansh': 'rm',
        'Romanian; Moldavian; Moldovan': 'ro',
        'Rundi': 'rn',
        'Russian': 'ru',
        'Sango': 'sg',
        'Sanskrit': 'sa',
        'Sinhala; Sinhalese': 'si',
        'Slovak': 'sk',
        'Slovenian': 'sl',
        'Northern Sami': 'se',
        'Samoan': 'sm',
        'Shona': 'sn',
        'Sindhi': 'sd',
        'Somali': 'so',
        'Sotho, Southern': 'st',
        'Spanish; Castilian': 'es',
        'Sardinian': 'sc',
        'Serbian': 'sr',
        'Swati': 'ss',
        'Sundanese': 'su',
        'Swahili': 'sw',
        'Swedish': 'sv',
        'Tahitian': 'ty',
        'Tamil': 'ta',
        'Tatar': 'tt',
        'Telugu': 'te',
        'Tajik': 'tg',
        'Tagalog': 'tl',
        'Thai': 'th',
        'Tibetan': 'bo',
        'Tigrinya': 'ti',
        'Tonga (Tonga Islands)': 'to',
        'Tswana': 'tn',
        'Tsonga': 'ts',
        'Turkmen': 'tk',
        'Turkish': 'tr',
        'Twi': 'tw',
        'Uighur; Uyghur': 'ug',
        'Ukrainian': 'uk',
        'Urdu': 'ur',
        'Uzbek': 'uz',
        'Venda': 've',
        'Vietnamese': 'vi',
        'Volapük': 'vo',
        'Welsh': 'cy',
        'Walloon': 'wa',
        'Wolof': 'wo',
        'Xhosa': 'xh',
        'Yiddish': 'yi',
        'Yoruba': 'yo',
        'Zhuang; Chuang': 'za',
        'Zulu': 'zu',
    }

    CODE3: ClassVar = {
        'Afar': 'aar',
        'Abkhazian': 'abk',
        'Afrikaans': 'afr',
        'Akan': 'aka',
        'Albanian': 'alb',
        'Amharic': 'amh',
        'Arabic': 'ara',
        'Aragonese': 'arg',
        'Armenian': 'arm',
        'Assamese': 'asm',
        'Avaric': 'ava',
        'Avestan': 'ave',
        'Aymara': 'aym',
        'Azerbaijani': 'aze',
        'Bashkir': 'bak',
        'Bambara': 'bam',
        'Basque': 'baq',
        'Belarusian': 'bel',
        'Bengali': 'ben',
        'Bislama': 'bis',
        'Bosnian': 'bos',
        'Breton': 'bre',
        'Bulgarian': 'bul',
        'Burmese': 'bur',
        'Catalan; Valencian': 'cat',
        'Chamorro': 'cha',
        'Chechen': 'che',
        'Chinese': 'chi',
        'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic': 'chu',
        'Chuvash': 'chv',
        'Cornish': 'cor',
        'Corsican': 'cos',
        'Cree': 'cre',
        'Czech': 'cze',
        'Danish': 'dan',
        'Divehi; Dhivehi; Maldivian': 'div',
        'Dutch; Flemish': 'dut',
        'Dzongkha': 'dzo',
        'English': 'eng',
        'Esperanto': 'epo',
        'Estonian': 'est',
        'Ewe': 'ewe',
        'Faroese': 'fao',
        'Fijian': 'fij',
        'Finnish': 'fin',
        'French': 'fre',
        'Western Frisian': 'fry',
        'Fulah': 'ful',
        'Georgian': 'geo',
        'German': 'ger',
        'Gaelic; Scottish Gaelic': 'gla',
        'Irish': 'gle',
        'Galician': 'glg',
        'Manx': 'glv',
        'Greek, Modern (1453-)': 'gre',
        'Guarani': 'grn',
        'Gujarati': 'guj',
        'Haitian; Haitian Creole': 'hat',
        'Hausa': 'hau',
        'Hebrew': 'heb',
        'Herero': 'her',
        'Hindi': 'hin',
        'Hiri Motu': 'hmo',
        'Croatian': 'hrv',
        'Hungarian': 'hun',
        'Igbo': 'ibo',
        'Icelandic': 'ice',
        'Ido': 'ido',
        'Sichuan Yi; Nuosu': 'iii',
        'Inuktitut': 'iku',
        'Interlingue; Occidental': 'ile',
        'Interlingua (International Auxiliary Language Association)': 'ina',
        'Indonesian': 'ind',
        'Inupiaq': 'ipk',
        'Italian': 'ita',
        'Javanese': 'jav',
        'Japanese': 'jpn',
        'Kalaallisut; Greenlandic': 'kal',
        'Kannada': 'kan',
        'Kashmiri': 'kas',
        'Kanuri': 'kau',
        'Kazakh': 'kaz',
        'Central Khmer': 'khm',
        'Kikuyu; Gikuyu': 'kik',
        'Kinyarwanda': 'kin',
        'Kirghiz; Kyrgyz': 'kir',
        'Komi': 'kom',
        'Kongo': 'kon',
        'Korean': 'kor',
        'Kuanyama; Kwanyama': 'kua',
        'Kurdish': 'kur',
        'Lao': 'lao',
        'Latin': 'lat',
        'Latvian': 'lav',
        'Limburgan; Limburger; Limburgish': 'lim',
        'Lingala': 'lin',
        'Lithuanian': 'lit',
        'Luxembourgish; Letzeburgesch': 'ltz',
        'Luba-Katanga': 'lub',
        'Ganda': 'lug',
        'Macedonian': 'mac',
        'Marshallese': 'mah',
        'Malayalam': 'mal',
        'Maori': 'mao',
        'Marathi': 'mar',
        'Malay': 'may',
        'Malagasy': 'mlg',
        'Maltese': 'mlt',
        'Mongolian': 'mon',
        'Nauru': 'nau',
        'Navajo; Navaho': 'nav',
        'Ndebele, South; South Ndebele': 'nbl',
        'Ndebele, North; North Ndebele': 'nde',
        'Ndonga': 'ndo',
        'Nepali': 'nep',
        'Norwegian Nynorsk; Nynorsk, Norwegian': 'nno',
        'Bokmål, Norwegian; Norwegian Bokmål': 'nob',
        'Norwegian': 'nor',
        'Chichewa; Chewa; Nyanja': 'nya',
        'Occitan (post 1500)': 'oci',
        'Ojibwa': 'oji',
        'Oriya': 'ori',
        'Oromo': 'orm',
        'Ossetian; Ossetic': 'oss',
        'Panjabi; Punjabi': 'pan',
        'Persian': 'per',
        'Pali': 'pli',
        'Polish': 'pol',
        'Portuguese': 'por',
        'Pushto; Pashto': 'pus',
        'Quechua': 'que',
        'Romansh': 'roh',
        'Romanian; Moldavian; Moldovan': 'rum',
        'Rundi': 'run',
        'Russian': 'rus',
        'Sango': 'sag',
        'Sanskrit': 'san',
        'Sinhala; Sinhalese': 'sin',
        'Slovak': 'slo',
        'Slovenian': 'slv',
        'Northern Sami': 'sme',
        'Samoan': 'smo',
        'Shona': 'sna',
        'Sindhi': 'snd',
        'Somali': 'som',
        'Sotho, Southern': 'sot',
        'Spanish; Castilian': 'spa',
        'Sardinian': 'srd',
        'Serbian': 'srp',
        'Swati': 'ssw',
        'Sundanese': 'sun',
        'Swahili': 'swa',
        'Swedish': 'swe',
        'Tahitian': 'tah',
        'Tamil': 'tam',
        'Tatar': 'tat',
        'Telugu': 'tel',
        'Tajik': 'tgk',
        'Tagalog': 'tgl',
        'Thai': 'tha',
        'Tibetan': 'tib',
        'Tigrinya': 'tir',
        'Tonga (Tonga Islands)': 'ton',
        'Tswana': 'tsn',
        'Tsonga': 'tso',
        'Turkmen': 'tuk',
        'Turkish': 'tur',
        'Twi': 'twi',
        'Uighur; Uyghur': 'uig',
        'Ukrainian': 'ukr',
        'Urdu': 'urd',
        'Uzbek': 'uzb',
        'Venda': 'ven',
        'Vietnamese': 'vie',
        'Volapük': 'vol',
        'Welsh': 'wel',
        'Walloon': 'wln',
        'Wolof': 'wol',
        'Xhosa': 'xho',
        'Yiddish': 'yid',
        'Yoruba': 'yor',
        'Zhuang; Chuang': 'zha',
        'Zulu': 'zul',
    }