# Licensed under a 3-clause BSD style license - see LICENSE.md
"""Add a dictionary to find the ISO 639-1 language code."""

from typing import ClassVar


class Lang:
    """ISO 639-1 codes for languages.

    The GEDCOM standard requires the use of ISO 639-1 codes for
    languages. This is available in the CODE dictionary.

    However, the standard allows an extension code for three-character
    ISO 639-2 codes.  This is available in the CODE3 dictionary.

    Reference:
        - [Library of Congress Data](https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt)
        - [ISO 639-1 and 639-2 Library of Congress](https://www.loc.gov/standards/iso639-2/langhome.html#top)
        - [ISO-1 Maintenance Agency](http://www.infoterm.info/standardization/iso_639_1_2002.php)
        - [ISO Language Standards](https://www.iso.org/iso-639-language-code)
        - [GEDCOM Standard]()
    """

    CODE: ClassVar = {
        "Afar": "aa",
        "Abkhazian": "ab",
        "Afrikaans": "af",
        "Akan": "ak",
        "Albanian": "sq",
        "Amharic": "am",
        "Arabic": "ar",
        "Aragonese": "an",
        "Armenian": "hy",
        "Assamese": "as",
        "Avaric": "av",
        "Avestan": "ae",
        "Aymara": "ay",
        "Azerbaijani": "az",
        "Bashkir": "ba",
        "Bambara": "bm",
        "Basque": "eu",
        "Belarusian": "be",
        "Bengali": "bn",
        "Bislama": "bi",
        "Bosnian": "bs",
        "Breton": "br",
        "Bulgarian": "bg",
        "Burmese": "my",
        "Catalan": "ca",
        "Valencian": "ca",
        "Chamorro": "ch",
        "Chechen": "ce",
        "Chinese": "zh",
        "Church Slavic": "cu",
        "Old Slavonic": "cu",
        "Church Slavonic": "cu",
        "Old Bulgarian": "cu",
        "Old Church Slavonic": "cu",
        "Chuvash": "cv",
        "Cornish": "kw",
        "Corsican": "co",
        "Cree": "cr",
        "Czech": "cs",
        "Danish": "da",
        "Divehi": "dv",
        "Dhivehi": "dv",
        "Maldivian": "dv",
        "Dutch": "nl",
        "Flemish": "nl",
        "Dzongkha": "dz",
        "English": "en",
        "Esperanto": "eo",
        "Estonian": "et",
        "Ewe": "ee",
        "Faroese": "fo",
        "Fijian": "fj",
        "Finnish": "fi",
        "French": "fr",
        "Western Frisian": "fy",
        "Fulah": "ff",
        "Georgian": "ka",
        "German": "de",
        "Gaelic": "gd",
        "Scottish Gaelic": "gd",
        "Irish": "ga",
        "Galician": "gl",
        "Manx": "gv",
        "Greek, Modern (1453-)": "el",
        "Guarani": "gn",
        "Gujarati": "gu",
        "Haitian": "ht",
        "Haitian Creole": "ht",
        "Hausa": "ha",
        "Hebrew": "he",
        "Herero": "hz",
        "Hindi": "hi",
        "Hiri Motu": "ho",
        "Croatian": "hr",
        "Hungarian": "hu",
        "Igbo": "ig",
        "Icelandic": "is",
        "Ido": "io",
        "Sichuan Yi": "ii",
        "Nuosu": "ii",
        "Inuktitut": "iu",
        "Interlingue": "ie",
        "Occidental": "ie",
        "Interlingua (International Auxiliary Language Association)": "ia",
        "Indonesian": "id",
        "Inupiaq": "ik",
        "Italian": "it",
        "Javanese": "jv",
        "Japanese": "ja",
        "Kalaallisut": "kl",
        "Greenlandic": "kl",
        "Kannada": "kn",
        "Kashmiri": "ks",
        "Kanuri": "kr",
        "Kazakh": "kk",
        "Central Khmer": "km",
        "Kikuyu": "ki",
        "Gikuyu": "ki",
        "Kinyarwanda": "rw",
        "Kirghiz": "ky",
        "Kyrgyz": "ky",
        "Komi": "kv",
        "Kongo": "kg",
        "Korean": "ko",
        "Kuanyama": "kj",
        "Kwanyama": "kj",
        "Kurdish": "ku",
        "Lao": "lo",
        "Latin": "la",
        "Latvian": "lv",
        "Limburgan": "li",
        "Limburger": "li",
        "Limburgish": "li",
        "Lingala": "ln",
        "Lithuanian": "lt",
        "Luxembourgish": "lb",
        "Letzeburgesch": "lb",
        "Luba-Katanga": "lu",
        "Ganda": "lg",
        "Macedonian": "mk",
        "Marshallese": "mh",
        "Malayalam": "ml",
        "Maori": "mi",
        "Marathi": "mr",
        "Malay": "ms",
        "Malagasy": "mg",
        "Maltese": "mt",
        "Mongolian": "mn",
        "Nauru": "na",
        "Navajo": "nv",
        "Navaho": "nv",
        "Ndebele, South": "nr",
        "South Ndebele": "nr",
        "Ndebele, North": "nd",
        "North Ndebele": "nd",
        "Ndonga": "ng",
        "Nepali": "ne",
        "Norwegian Nynorsk": "nn",
        "Nynorsk, Norwegian": "nn",
        "Bokmål, Norwegian": "nb",
        "Norwegian Bokmål": "nb",
        "Norwegian": "no",
        "Chichewa": "ny",
        "Chewa": "ny",
        "Nyanja": "ny",
        "Occitan (post 1500)": "oc",
        "Ojibwa": "oj",
        "Oriya": "or",
        "Oromo": "om",
        "Ossetian": "os",
        "Ossetic": "os",
        "Panjabi": "pa",
        "Punjabi": "pa",
        "Persian": "fa",
        "Pali": "pi",
        "Polish": "pl",
        "Portuguese": "pt",
        "Pushto": "ps",
        "Pashto": "ps",
        "Quechua": "qu",
        "Romansh": "rm",
        "Romanian": "ro",
        "Moldavian": "ro",
        "Moldovan": "ro",
        "Rundi": "rn",
        "Russian": "ru",
        "Sango": "sg",
        "Sanskrit": "sa",
        "Sinhala": "si",
        "Sinhalese": "si",
        "Slovak": "sk",
        "Slovenian": "sl",
        "Northern Sami": "se",
        "Samoan": "sm",
        "Shona": "sn",
        "Sindhi": "sd",
        "Somali": "so",
        "Sotho, Southern": "st",
        "Spanish": "es",
        "Castilian": "es",
        "Sardinian": "sc",
        "Serbian": "sr",
        "Swati": "ss",
        "Sundanese": "su",
        "Swahili": "sw",
        "Swedish": "sv",
        "Tahitian": "ty",
        "Tamil": "ta",
        "Tatar": "tt",
        "Telugu": "te",
        "Tajik": "tg",
        "Tagalog": "tl",
        "Thai": "th",
        "Tibetan": "bo",
        "Tigrinya": "ti",
        "Tonga (Tonga Islands)": "to",
        "Tswana": "tn",
        "Tsonga": "ts",
        "Turkmen": "tk",
        "Turkish": "tr",
        "Twi": "tw",
        "Uighur": "ug",
        "Uyghur": "ug",
        "Ukrainian": "uk",
        "Urdu": "ur",
        "Uzbek": "uz",
        "Venda": "ve",
        "Vietnamese": "vi",
        "Volapük": "vo",
        "Welsh": "cy",
        "Walloon": "wa",
        "Wolof": "wo",
        "Xhosa": "xh",
        "Yiddish": "yi",
        "Yoruba": "yo",
        "Zhuang": "za",
        "Chuang": "za",
        "Zulu": "zu",
        "NONE": "",
    }

    CODE3: ClassVar = {
        "Afar": "aar",
        "Abkhazian": "abk",
        "Achinese": "ace",
        "Acoli": "ach",
        "Adangme": "ada",
        "Adyghe": "ady",
        "Adygei": "ady",
        "Afro-Asiatic languages": "afa",
        "Afrihili": "afh",
        "Afrikaans": "afr",
        "Ainu": "ain",
        "Akan": "aka",
        "Akkadian": "akk",
        "Albanian": "alb",
        "Aleut": "ale",
        "Algonquian languages": "alg",
        "Southern Altai": "alt",
        "Amharic": "amh",
        "English, Old (ca.450-1100)": "ang",
        "Angika": "anp",
        "Apache languages": "apa",
        "Arabic": "ara",
        "Official Aramaic (700-300 BCE)": "arc",
        "Imperial Aramaic (700-300 BCE)": "arc",
        "Aragonese": "arg",
        "Armenian": "arm",
        "Mapudungun": "arn",
        "Mapuche": "arn",
        "Arapaho": "arp",
        "Artificial languages": "art",
        "Arawak": "arw",
        "Assamese": "asm",
        "Asturian": "ast",
        "Bable": "ast",
        "Leonese": "ast",
        "Asturleonese": "ast",
        "Athapascan languages": "ath",
        "Australian languages": "aus",
        "Avaric": "ava",
        "Avestan": "ave",
        "Awadhi": "awa",
        "Aymara": "aym",
        "Azerbaijani": "aze",
        "Banda languages": "bad",
        "Bamileke languages": "bai",
        "Bashkir": "bak",
        "Baluchi": "bal",
        "Bambara": "bam",
        "Balinese": "ban",
        "Basque": "baq",
        "Basa": "bas",
        "Baltic languages": "bat",
        "Beja": "bej",
        "Bedawiyet": "bej",
        "Belarusian": "bel",
        "Bemba": "bem",
        "Bengali": "ben",
        "Berber languages": "ber",
        "Bhojpuri": "bho",
        "Bihari languages": "bih",
        "Bikol": "bik",
        "Bini": "bin",
        "Edo": "bin",
        "Bislama": "bis",
        "Siksika": "bla",
        "Bantu languages": "bnt",
        "Bosnian": "bos",
        "Braj": "bra",
        "Breton": "bre",
        "Batak languages": "btk",
        "Buriat": "bua",
        "Buginese": "bug",
        "Bulgarian": "bul",
        "Burmese": "bur",
        "Blin": "byn",
        "Bilin": "byn",
        "Caddo": "cad",
        "Central American Indian languages": "cai",
        "Galibi Carib": "car",
        "Catalan": "cat",
        "Valencian": "cat",
        "Caucasian languages": "cau",
        "Cebuano": "ceb",
        "Celtic languages": "cel",
        "Chamorro": "cha",
        "Chibcha": "chb",
        "Chechen": "che",
        "Chagatai": "chg",
        "Chinese": "chi",
        "Chuukese": "chk",
        "Mari": "chm",
        "Chinook jargon": "chn",
        "Choctaw": "cho",
        "Chipewyan": "chp",
        "Dene Suline": "chp",
        "Cherokee": "chr",
        "Church Slavic": "chu",
        "Old Slavonic": "chu",
        "Church Slavonic": "chu",
        "Old Bulgarian": "chu",
        "Old Church Slavonic": "chu",
        "Chuvash": "chv",
        "Cheyenne": "chy",
        "Chamic languages": "cmc",
        "Montenegrin": "cnr",
        "Coptic": "cop",
        "Cornish": "cor",
        "Corsican": "cos",
        "Creoles and pidgins, English based": "cpe",
        "Creoles and pidgins, French-based": "cpf",
        "Creoles and pidgins, Portuguese-based": "cpp",
        "Cree": "cre",
        "Crimean Tatar": "crh",
        "Crimean Turkish": "crh",
        "Creoles and pidgins": "crp",
        "Kashubian": "csb",
        "Cushitic languages": "cus",
        "Czech": "cze",
        "Dakota": "dak",
        "Danish": "dan",
        "Dargwa": "dar",
        "Land Dayak languages": "day",
        "Delaware": "del",
        "Slave (Athapascan)": "den",
        "Tlicho": "dgr",
        "Dogrib": "dgr",
        "Dinka": "din",
        "Divehi": "div",
        "Dhivehi": "div",
        "Maldivian": "div",
        "Dogri": "doi",
        "Dravidian languages": "dra",
        "Lower Sorbian": "dsb",
        "Duala": "dua",
        "Dutch, Middle (ca.1050-1350)": "dum",
        "Dutch": "dut",
        "Flemish": "dut",
        "Dyula": "dyu",
        "Dzongkha": "dzo",
        "Efik": "efi",
        "Egyptian (Ancient)": "egy",
        "Ekajuk": "eka",
        "Elamite": "elx",
        "English": "eng",
        "English, Middle (1100-1500)": "enm",
        "Esperanto": "epo",
        "Estonian": "est",
        "Ewe": "ewe",
        "Ewondo": "ewo",
        "Fang": "fan",
        "Faroese": "fao",
        "Fanti": "fat",
        "Fijian": "fij",
        "Filipino": "fil",
        "Pilipino": "fil",
        "Finnish": "fin",
        "Finno-Ugrian languages": "fiu",
        "Fon": "fon",
        "French": "fre",
        "French, Middle (ca.1400-1600)": "frm",
        "French, Old (842-ca.1400)": "fro",
        "Northern Frisian": "frr",
        "Eastern Frisian": "frs",
        "Western Frisian": "fry",
        "Fulah": "ful",
        "Friulian": "fur",
        "Ga": "gaa",
        "Gayo": "gay",
        "Gbaya": "gba",
        "Germanic languages": "gem",
        "Georgian": "geo",
        "German": "ger",
        "Geez": "gez",
        "Gilbertese": "gil",
        "Gaelic": "gla",
        "Scottish Gaelic": "gla",
        "Irish": "gle",
        "Galician": "glg",
        "Manx": "glv",
        "German, Middle High (ca.1050-1500)": "gmh",
        "German, Old High (ca.750-1050)": "goh",
        "Gondi": "gon",
        "Gorontalo": "gor",
        "Gothic": "got",
        "Grebo": "grb",
        "Greek, Ancient (to 1453)": "grc",
        "Greek, Modern (1453-)": "gre",
        "Guarani": "grn",
        "Swiss German": "gsw",
        "Alemannic": "gsw",
        "Alsatian": "gsw",
        "Gujarati": "guj",
        "Gwich'in": "gwi",
        "Haida": "hai",
        "Haitian": "hat",
        "Haitian Creole": "hat",
        "Hausa": "hau",
        "Hawaiian": "haw",
        "Hebrew": "heb",
        "Herero": "her",
        "Hiligaynon": "hil",
        "Himachali languages": "him",
        "Western Pahari languages": "him",
        "Hindi": "hin",
        "Hittite": "hit",
        "Hmong": "hmn",
        "Mong": "hmn",
        "Hiri Motu": "hmo",
        "Croatian": "hrv",
        "Upper Sorbian": "hsb",
        "Hungarian": "hun",
        "Hupa": "hup",
        "Iban": "iba",
        "Igbo": "ibo",
        "Icelandic": "ice",
        "Ido": "ido",
        "Sichuan Yi": "iii",
        "Nuosu": "iii",
        "Ijo languages": "ijo",
        "Inuktitut": "iku",
        "Interlingue": "ile",
        "Occidental": "ile",
        "Iloko": "ilo",
        "Interlingua (International Auxiliary Language Association)": "ina",
        "Indic languages": "inc",
        "Indonesian": "ind",
        "Indo-European languages": "ine",
        "Ingush": "inh",
        "Inupiaq": "ipk",
        "Iranian languages": "ira",
        "Iroquoian languages": "iro",
        "Italian": "ita",
        "Javanese": "jav",
        "Lojban": "jbo",
        "Japanese": "jpn",
        "Judeo-Persian": "jpr",
        "Judeo-Arabic": "jrb",
        "Kara-Kalpak": "kaa",
        "Kabyle": "kab",
        "Kachin": "kac",
        "Jingpho": "kac",
        "Kalaallisut": "kal",
        "Greenlandic": "kal",
        "Kamba": "kam",
        "Kannada": "kan",
        "Karen languages": "kar",
        "Kashmiri": "kas",
        "Kanuri": "kau",
        "Kawi": "kaw",
        "Kazakh": "kaz",
        "Kabardian": "kbd",
        "Khasi": "kha",
        "Khoisan languages": "khi",
        "Central Khmer": "khm",
        "Khotanese": "kho",
        "Sakan": "kho",
        "Kikuyu": "kik",
        "Gikuyu": "kik",
        "Kinyarwanda": "kin",
        "Kirghiz": "kir",
        "Kyrgyz": "kir",
        "Kimbundu": "kmb",
        "Konkani": "kok",
        "Komi": "kom",
        "Kongo": "kon",
        "Korean": "kor",
        "Kosraean": "kos",
        "Kpelle": "kpe",
        "Karachay-Balkar": "krc",
        "Karelian": "krl",
        "Kru languages": "kro",
        "Kurukh": "kru",
        "Kuanyama": "kua",
        "Kwanyama": "kua",
        "Kumyk": "kum",
        "Kurdish": "kur",
        "Kutenai": "kut",
        "Ladino": "lad",
        "Lahnda": "lah",
        "Lamba": "lam",
        "Lao": "lao",
        "Latin": "lat",
        "Latvian": "lav",
        "Lezghian": "lez",
        "Limburgan": "lim",
        "Limburger": "lim",
        "Limburgish": "lim",
        "Lingala": "lin",
        "Lithuanian": "lit",
        "Mongo": "lol",
        "Lozi": "loz",
        "Luxembourgish": "ltz",
        "Letzeburgesch": "ltz",
        "Luba-Lulua": "lua",
        "Luba-Katanga": "lub",
        "Ganda": "lug",
        "Luiseno": "lui",
        "Lunda": "lun",
        "Luo (Kenya and Tanzania)": "luo",
        "Lushai": "lus",
        "Macedonian": "mac",
        "Madurese": "mad",
        "Magahi": "mag",
        "Marshallese": "mah",
        "Maithili": "mai",
        "Makasar": "mak",
        "Malayalam": "mal",
        "Mandingo": "man",
        "Maori": "mao",
        "Austronesian languages": "map",
        "Marathi": "mar",
        "Masai": "mas",
        "Malay": "may",
        "Moksha": "mdf",
        "Mandar": "mdr",
        "Mende": "men",
        "Irish, Middle (900-1200)": "mga",
        "Mi'kmaq": "mic",
        "Micmac": "mic",
        "Minangkabau": "min",
        "Uncoded languages": "mis",
        "Mon-Khmer languages": "mkh",
        "Malagasy": "mlg",
        "Maltese": "mlt",
        "Manchu": "mnc",
        "Manipuri": "mni",
        "Manobo languages": "mno",
        "Mohawk": "moh",
        "Mongolian": "mon",
        "Mossi": "mos",
        "Multiple languages": "mul",
        "Munda languages": "mun",
        "Creek": "mus",
        "Mirandese": "mwl",
        "Marwari": "mwr",
        "Mayan languages": "myn",
        "Erzya": "myv",
        "Nahuatl languages": "nah",
        "North American Indian languages": "nai",
        "Neapolitan": "nap",
        "Nauru": "nau",
        "Navajo": "nav",
        "Navaho": "nav",
        "Ndebele, South": "nbl",
        "South Ndebele": "nbl",
        "Ndebele, North": "nde",
        "North Ndebele": "nde",
        "Ndonga": "ndo",
        "Low German": "nds",
        "Low Saxon": "nds",
        "German, Low": "nds",
        "Saxon, Low": "nds",
        "Nepali": "nep",
        "Nepal Bhasa": "new",
        "Newari": "new",
        "Nias": "nia",
        "Niger-Kordofanian languages": "nic",
        "Niuean": "niu",
        "Norwegian Nynorsk": "nno",
        "Nynorsk, Norwegian": "nno",
        "Bokmål, Norwegian": "nob",
        "Norwegian Bokmål": "nob",
        "Nogai": "nog",
        "Norse, Old": "non",
        "Norwegian": "nor",
        "N'Ko": "nqo",
        "Pedi": "nso",
        "Sepedi": "nso",
        "Northern Sotho": "nso",
        "Nubian languages": "nub",
        "Classical Newari": "nwc",
        "Old Newari": "nwc",
        "Classical Nepal Bhasa": "nwc",
        "Chichewa": "nya",
        "Chewa": "nya",
        "Nyanja": "nya",
        "Nyamwezi": "nym",
        "Nyankole": "nyn",
        "Nyoro": "nyo",
        "Nzima": "nzi",
        "Occitan (post 1500)": "oci",
        "Ojibwa": "oji",
        "Oriya": "ori",
        "Oromo": "orm",
        "Osage": "osa",
        "Ossetian": "oss",
        "Ossetic": "oss",
        "Turkish, Ottoman (1500-1928)": "ota",
        "Otomian languages": "oto",
        "Papuan languages": "paa",
        "Pangasinan": "pag",
        "Pahlavi": "pal",
        "Pampanga": "pam",
        "Kapampangan": "pam",
        "Panjabi": "pan",
        "Punjabi": "pan",
        "Papiamento": "pap",
        "Palauan": "pau",
        "Persian, Old (ca.600-400 B.C.)": "peo",
        "Persian": "per",
        "Philippine languages": "phi",
        "Phoenician": "phn",
        "Pali": "pli",
        "Polish": "pol",
        "Pohnpeian": "pon",
        "Portuguese": "por",
        "Prakrit languages": "pra",
        "Provençal, Old (to 1500)": "pro",
        "Occitan, Old (to 1500)": "pro",
        "Pushto": "pus",
        "Pashto": "pus",
        "Reserved for local use": "qaa-qtz",
        "Quechua": "que",
        "Rajasthani": "raj",
        "Rapanui": "rap",
        "Rarotongan": "rar",
        "Cook Islands Maori": "rar",
        "Romance languages": "roa",
        "Romansh": "roh",
        "Romany": "rom",
        "Romanian": "rum",
        "Moldavian": "rum",
        "Moldovan": "rum",
        "Rundi": "run",
        "Aromanian": "rup",
        "Arumanian": "rup",
        "Macedo-Romanian": "rup",
        "Russian": "rus",
        "Sandawe": "sad",
        "Sango": "sag",
        "Yakut": "sah",
        "South American Indian languages": "sai",
        "Salishan languages": "sal",
        "Samaritan Aramaic": "sam",
        "Sanskrit": "san",
        "Sasak": "sas",
        "Santali": "sat",
        "Sicilian": "scn",
        "Scots": "sco",
        "Selkup": "sel",
        "Semitic languages": "sem",
        "Irish, Old (to 900)": "sga",
        "Sign Languages": "sgn",
        "Shan": "shn",
        "Sidamo": "sid",
        "Sinhala": "sin",
        "Sinhalese": "sin",
        "Siouan languages": "sio",
        "Sino-Tibetan languages": "sit",
        "Slavic languages": "sla",
        "Slovak": "slo",
        "Slovenian": "slv",
        "Southern Sami": "sma",
        "Northern Sami": "sme",
        "Sami languages": "smi",
        "Lule Sami": "smj",
        "Inari Sami": "smn",
        "Samoan": "smo",
        "Skolt Sami": "sms",
        "Shona": "sna",
        "Sindhi": "snd",
        "Soninke": "snk",
        "Sogdian": "sog",
        "Somali": "som",
        "Songhai languages": "son",
        "Sotho, Southern": "sot",
        "Spanish": "spa",
        "Castilian": "spa",
        "Sardinian": "srd",
        "Sranan Tongo": "srn",
        "Serbian": "srp",
        "Serer": "srr",
        "Nilo-Saharan languages": "ssa",
        "Swati": "ssw",
        "Sukuma": "suk",
        "Sundanese": "sun",
        "Susu": "sus",
        "Sumerian": "sux",
        "Swahili": "swa",
        "Swedish": "swe",
        "Classical Syriac": "syc",
        "Syriac": "syr",
        "Tahitian": "tah",
        "Tai languages": "tai",
        "Tamil": "tam",
        "Tatar": "tat",
        "Telugu": "tel",
        "Timne": "tem",
        "Tereno": "ter",
        "Tetum": "tet",
        "Tajik": "tgk",
        "Tagalog": "tgl",
        "Thai": "tha",
        "Tibetan": "tib",
        "Tigre": "tig",
        "Tigrinya": "tir",
        "Tiv": "tiv",
        "Tokelau": "tkl",
        "Klingon": "tlh",
        "tlhIngan-Hol": "tlh",
        "Tlingit": "tli",
        "Tamashek": "tmh",
        "Tonga (Nyasa)": "tog",
        "Tonga (Tonga Islands)": "ton",
        "Tok Pisin": "tpi",
        "Tsimshian": "tsi",
        "Tswana": "tsn",
        "Tsonga": "tso",
        "Turkmen": "tuk",
        "Tumbuka": "tum",
        "Tupi languages": "tup",
        "Turkish": "tur",
        "Altaic languages": "tut",
        "Tuvalu": "tvl",
        "Twi": "twi",
        "Tuvinian": "tyv",
        "Udmurt": "udm",
        "Ugaritic": "uga",
        "Uighur": "uig",
        "Uyghur": "uig",
        "Ukrainian": "ukr",
        "Umbundu": "umb",
        "Undetermined": "und",
        "Urdu": "urd",
        "Uzbek": "uzb",
        "Vai": "vai",
        "Venda": "ven",
        "Vietnamese": "vie",
        "Volapük": "vol",
        "Votic": "vot",
        "Wakashan languages": "wak",
        "Wolaitta": "wal",
        "Wolaytta": "wal",
        "Waray": "war",
        "Washo": "was",
        "Welsh": "wel",
        "Sorbian languages": "wen",
        "Walloon": "wln",
        "Wolof": "wol",
        "Kalmyk": "xal",
        "Oirat": "xal",
        "Xhosa": "xho",
        "Yao": "yao",
        "Yapese": "yap",
        "Yiddish": "yid",
        "Yoruba": "yor",
        "Yupik languages": "ypk",
        "Zapotec": "zap",
        "Blissymbols": "zbl",
        "Blissymbolics": "zbl",
        "Bliss": "zbl",
        "Zenaga": "zen",
        "Standard Moroccan Tamazight": "zgh",
        "Zhuang": "zha",
        "Chuang": "zha",
        "Zande languages": "znd",
        "Zulu": "zul",
        "Zuni": "zun",
        "No linguistic content": "zxx",
        "Not applicable": "zxx",
        "Zaza": "zza",
        "Dimili": "zza",
        "Dimli": "zza",
        "Kirdki": "zza",
        "Kirmanjki": "zza",
        "Zazaki": "zza",
        "NONE": "",
    }